<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CuisineTableSeeder extends Seeder {
    public function run() {
        DB::table('cuisines')
          ->delete();
        DB::statement('ALTER TABLE cuisines AUTO_INCREMENT = 0;');

        $cuisines = [
            ['s2' => 'AFRICAN', 'cuisine' => 'AFRICAN', 'meta' => null],
            ['s2' => 'AFRICN', 'cuisine' => 'AFRICAN', 'meta' => null],
            ['s2' => 'ETH', 'cuisine' => 'AFRICAN', 'meta' => 'ETHIOPIAN'],
            ['s2' => 'ETHIO', 'cuisine' => 'AFRICAN', 'meta' => 'ETHIOPIAN'],
            ['s2' => 'ETHIOP', 'cuisine' => 'AFRICAN', 'meta' => 'ETHIOPIAN'],
            ['s2' => 'ETHIOPIAN', 'cuisine' => 'AFRICAN', 'meta' => 'ETHIOPIAN'],
            ['s2' => 'ETHIOPN', 'cuisine' => 'AFRICAN', 'meta' => 'ETHIOPIAN'],
            ['s2' => 'NIGERIAN', 'cuisine' => 'AFRICAN', 'meta' => 'NIGERIAN'],
            ['s2' => 'AM/CA', 'cuisine' => 'AMERICAN', 'meta' => 'CALIFORNIAN'],
            ['s2' => 'AM/CRP', 'cuisine' => 'AMERICAN', 'meta' => null ],
            ['s2' => 'AM/DANISH', 'cuisine' => 'AMERICAN', 'meta' => 'DANISH, FUSION'],
            ['s2' => 'AMERICAN', 'cuisine' => 'AMERICAN', 'meta' => 'CONTINENTAL'],
            ['s2' => 'AMR', 'cuisine' => 'AMERICAN', 'meta' => 'CONTINENTAL'],
            ['s2' => 'BPH', 'cuisine' => 'AMERICAN', 'meta' => 'BREAKFAST, PANCAKE, WAFFLE'],
            ['s2' => 'CALIFR', 'cuisine' => 'AMERICAN', 'meta' => 'CALIFORNIAN'],
            ['s2' => 'CALIFRN', 'cuisine' => 'AMERICAN', 'meta' => 'CALIFORNIAN'],
            ['s2' => 'CHICKEN', 'cuisine' => 'AMERICAN', 'meta' => 'CHICKEN'],
            ['s2' => 'CHICKN', 'cuisine' => 'AMERICAN', 'meta' => 'CHICKEN'],
            ['s2' => 'CHK', 'cuisine' => 'AMERICAN', 'meta' => 'CHICKEN'],
            ['s2' => 'CMP', 'cuisine' => 'AMERICAN', 'meta' => 'CAMP'],
            ['s2' => 'CNT AM', 'cuisine' => 'AMERICAN', 'meta' => null ],
            ['s2' => 'CON', 'cuisine' => 'AMERICAN', 'meta' => 'CONTINENTAL'],
            ['s2' => 'CONTEM', 'cuisine' => 'AMERICAN', 'meta' => null ],
            ['s2' => 'COU', 'cuisine' => 'AMERICAN', 'meta' => 'COUNTRY COOKING'],
            ['s2' => 'CRB/AM', 'cuisine' => 'AMERICAN', 'meta' => 'CARRIBEAN, FUSION'],
            ['s2' => 'DNR', 'cuisine' => 'AMERICAN', 'meta' => 'DINER'],
            ['s2' => 'NAT. AMERI', 'cuisine' => 'AMERICAN', 'meta' => null ],
            ['s2' => 'NEW AM', 'cuisine' => 'AMERICAN', 'meta' => null ],
            ['s2' => 'POT PIE', 'cuisine' => 'AMERICAN', 'meta' => null ],
            ['s2' => 'US/AMERICAN', 'cuisine' => 'AMERICAN', 'meta' => null ],
            ['s2' => 'AM/ASN', 'cuisine' => 'ASIAN', 'meta' => 'AMERICAN, FUSION, ORIENTAL'],
            ['s2' => 'ASIAN', 'cuisine' => 'ASIAN', 'meta' => 'ORIENTAL'],
            ['s2' => 'ASN FSN', 'cuisine' => 'ASIAN', 'meta' => 'FUSION, ORIENTAL'],
            ['s2' => 'ASN/AM', 'cuisine' => 'ASIAN', 'meta' => 'AMERICAN, FUSION, ORIENTAL'],
            ['s2' => 'BURMESE', 'cuisine' => 'ASIAN', 'meta' => 'BURMESE, ORIENTAL'],
            ['s2' => 'CA/ASN', 'cuisine' => 'ASIAN', 'meta' => 'CALIFORNIAN, ORIENTAL'],
            ['s2' => 'CHK/ASN', 'cuisine' => 'ASIAN', 'meta' => 'CHICKEN, ORIENTAL'],
            ['s2' => 'IDO', 'cuisine' => 'ASIAN', 'meta' => 'INDONESIA, ORIENTAL'],
            ['s2' => 'NOODLE', 'cuisine' => 'ASIAN', 'meta' => 'ORIENTAL'],
            ['s2' => 'ORN', 'cuisine' => 'ASIAN', 'meta' => 'ORIENTAL'],
            ['s2' => 'PAN ASIAN', 'cuisine' => 'ASIAN', 'meta' => 'ORIENTAL'],
            ['s2' => 'PANASN', 'cuisine' => 'ASIAN', 'meta' => 'ORIENTAL'],
            ['s2' => 'RAMEN', 'cuisine' => 'ASIAN', 'meta' => 'ORIENTAL'],
            ['s2' => 'SE ASIAN', 'cuisine' => 'ASIAN', 'meta' => 'SEAFOOD, ORIENTAL'],
            ['s2' => 'SEA/ASN', 'cuisine' => 'ASIAN', 'meta' => 'SEAFOOD, ORIENTAL'],
            ['s2' => 'STIR FRY', 'cuisine' => 'ASIAN', 'meta' => 'STIR FRY, ORIENTAL'],
            ['s2' => 'TER/AM', 'cuisine' => 'ASIAN', 'meta' => 'TERIYAKI, ORIENTAL'],
            ['s2' => 'TERIYAKI', 'cuisine' => 'ASIAN', 'meta' => 'TERIYAKI, ORIENTAL'],
            ['s2' => 'TERYAK', 'cuisine' => 'ASIAN', 'meta' => 'TERIYAKI, ORIENTAL'],
            ['s2' => 'BGL', 'cuisine' => 'BAGELS/DOUGHNUTS', 'meta' => 'BAKERY'],
            ['s2' => 'DNS', 'cuisine' => 'BAGELS/DOUGHNUTS', 'meta' => 'BAKERY, DONUT'],
            ['s2' => 'BAK', 'cuisine' => 'BAKERY', 'meta' => null ],
            ['s2' => 'BAKERY', 'cuisine' => 'BAKERY', 'meta' => null ],
            ['s2' => 'BAKERY CAF»', 'cuisine' => 'BAKERY', 'meta' => 'CAFÉ'],
            ['s2' => 'BAKERY CAFª', 'cuisine' => 'BAKERY', 'meta' => 'CAFÉ'],
            ['s2' => 'Bakery Cafe', 'cuisine' => 'BAKERY', 'meta' => 'CAFÉ'],
            ['s2' => 'BAKERY CAFÉ', 'cuisine' => 'BAKERY', 'meta' => 'CAFÉ'],
            ['s2' => 'PASTRY', 'cuisine' => 'BAKERY', 'meta' => 'PASTRY, CAKE, PIE, DONUT'],
            ['s2' => 'BAR', 'cuisine' => 'BAR', 'meta' => null ],
            ['s2' => 'BAR FOOD', 'cuisine' => 'BAR', 'meta' => null ],
            ['s2' => 'BRL', 'cuisine' => 'BAR', 'meta' => 'LOUNGE, CLUB, NIGHT CLUB'],
            ['s2' => 'CLUB BAR OR LOUNGE', 'cuisine' => 'BAR', 'meta' => 'LOUNGE, CLUB, NIGHT CLUB'],
            ['s2' => 'BBQ', 'cuisine' => 'BBQ', 'meta' => null ],
            ['s2' => 'BBQ/STHR', 'cuisine' => 'BBQ', 'meta' => 'SOUTHERN'],
            ['s2' => 'PRG/BBQ', 'cuisine' => 'BBQ', 'meta' => 'PORTUGUESE'],
            ['s2' => 'AM/ENG', 'cuisine' => 'BRITISH', 'meta' => 'ENGLISH, EURO'],
            ['s2' => 'Bread Pud', 'cuisine' => 'BRITISH', 'meta' => 'ENGLISH, EURO'],
            ['s2' => 'BRITISH', 'cuisine' => 'BRITISH', 'meta' => 'ENGLISH, EURO'],
            ['s2' => 'ENGLISH', 'cuisine' => 'BRITISH', 'meta' => 'ENGLISH, EURO'],
            ['s2' => 'Irish/British', 'cuisine' => 'BRITISH', 'meta' => 'ENGLISH, EURO, IRISH'],
            ['s2' => 'Irish/Brittish', 'cuisine' => 'BRITISH', 'meta' => 'ENGLISH, EURO, IRISH'],
            ['s2' => 'MEAT PIE', 'cuisine' => 'BRITISH', 'meta' => 'ENGLISH, EURO, MEAT PIE'],
            ['s2' => 'CAF»', 'cuisine' => 'CAFÉ', 'meta' => 'BAKERY'],
            ['s2' => 'CAFª', 'cuisine' => 'CAFÉ', 'meta' => 'BAKERY'],
            ['s2' => 'Cafe', 'cuisine' => 'CAFÉ', 'meta' => 'BAKERY'],
            ['s2' => 'CAFÈ', 'cuisine' => 'CAFÉ', 'meta' => 'BAKERY'],
            ['s2' => 'CREPE', 'cuisine' => 'CAFÉ', 'meta' => 'CREPE, BAKERY'],
            ['s2' => 'CREPES', 'cuisine' => 'CAFÉ', 'meta' => 'CREPE, BAKERY'],
            ['s2' => 'Crepes/Am', 'cuisine' => 'CAFÉ', 'meta' => 'CREPE, BAKERY'],
            ['s2' => 'CAJ', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'CAJ/CRL', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'CAJ/SEA', 'cuisine' => 'CAJUN/CREOLE', 'meta' => 'SEAFOOD'],
            ['s2' => 'CAJUN', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'CAJUN/CREOLE', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'CREOLE', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'CREOLE/CAJUN', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'CRL', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'GUMBO', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'NEW ORL', 'cuisine' => 'CAJUN/CREOLE', 'meta' => null ],
            ['s2' => 'AM/CRB', 'cuisine' => 'CARIBBEAN', 'meta' => 'FUSION, AMERICAN, GRILL'],
            ['s2' => 'AM/JMC', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN, AMERICAN, FUSION'],
            ['s2' => 'AMER/JAMA', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN, AMERICAN, FUSION, GRILL'],
            ['s2' => 'CAR', 'cuisine' => 'CARIBBEAN', 'meta' => null ],
            ['s2' => 'CARIB', 'cuisine' => 'CARIBBEAN', 'meta' => null ],
            ['s2' => 'CARIBBEAN', 'cuisine' => 'CARIBBEAN', 'meta' => null ],
            ['s2' => 'CARIBBN', 'cuisine' => 'CARIBBEAN', 'meta' => null ],
            ['s2' => 'CARIBN', 'cuisine' => 'CARIBBEAN', 'meta' => null ],
            ['s2' => 'DOMINC', 'cuisine' => 'CARIBBEAN', 'meta' => 'DOMINICAN REPUBLIC'],
            ['s2' => 'DOMINCN', 'cuisine' => 'CARIBBEAN', 'meta' => 'DOMINICAN REPUBLIC'],
            ['s2' => 'DOMINICA', 'cuisine' => 'CARIBBEAN', 'meta' => 'DOMINICAN REPUBLIC'],
            ['s2' => 'HAITIA', 'cuisine' => 'CARIBBEAN', 'meta' => 'HAITIAN'],
            ['s2' => 'HAITIAN', 'cuisine' => 'CARIBBEAN', 'meta' => 'HAITIAN'],
            ['s2' => 'JAMAI', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN'],
            ['s2' => 'JAMAIC', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN'],
            ['s2' => 'JAMAICA', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN'],
            ['s2' => 'JAMAICAN', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN'],
            ['s2' => 'JAMAICN', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN'],
            ['s2' => 'JAMICAN', 'cuisine' => 'CARIBBEAN', 'meta' => 'JAMACIAN'],
            ['s2' => 'PRT RCN', 'cuisine' => 'CARIBBEAN', 'meta' => 'DOMINICAN REPUBLIC'],
            ['s2' => 'PUERTO RCN', 'cuisine' => 'CARIBBEAN', 'meta' => 'PUERTO RICAN'],
            ['s2' => 'Cantonese', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'CHIN/AM', 'cuisine' => 'CHINESE', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'CHINES', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'CHINESE', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'CHINESE', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'CHINSE', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'CHN/MNG', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'CHN/SEA', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'CHS', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'MONGLN', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'MONGOLIAN', 'cuisine' => 'CHINESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'Szechuan', 'cuisine' => 'CHINESE', 'meta' => 'SZECHUAN, ASIAN, ORIENTAL'],
            ['s2' => 'CFS', 'cuisine' => 'COFFEE HOUSE', 'meta' => 'JAVA'],
            ['s2' => 'COFFEE', 'cuisine' => 'COFFEE HOUSE', 'meta' => 'JAVA'],
            ['s2' => 'COFFEEHOUSE', 'cuisine' => 'COFFEE HOUSE', 'meta' => 'JAVA'],
            ['s2' => 'CBN', 'cuisine' => 'CUBAN', 'meta' => null ],
            ['s2' => 'CUB/ITL', 'cuisine' => 'CUBAN', 'meta' => 'FUSION, ITALIAN, CARRIBEAN'],
            ['s2' => 'CUBAN', 'cuisine' => 'CUBAN', 'meta' => 'CARRIBEAN'],
            ['s2' => 'BAVARN', 'cuisine' => 'EUROPEAN', 'meta' => 'BAVARIAN'],
            ['s2' => 'BELGIAN', 'cuisine' => 'EUROPEAN', 'meta' => 'BELGIAN'],
            ['s2' => 'BELGN', 'cuisine' => 'EUROPEAN', 'meta' => 'BELGIAN'],
            ['s2' => 'CONTIN', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'CONTINT', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'CONTINTL', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'EASTERN EUROPEAN', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'EURO', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'Euro/Med', 'cuisine' => 'EUROPEAN', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'EUROPEAN', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'EUROPN', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'EURPN', 'cuisine' => 'EUROPEAN', 'meta' => null ],
            ['s2' => 'GRM', 'cuisine' => 'EUROPEAN', 'meta' => 'GERMAN'],
            ['s2' => 'POL', 'cuisine' => 'EUROPEAN', 'meta' => 'POLISH'],
            ['s2' => 'POLISH', 'cuisine' => 'EUROPEAN', 'meta' => 'POLISH'],
            ['s2' => 'POLISH/EUR', 'cuisine' => 'EUROPEAN', 'meta' => 'POLISH'],
            ['s2' => 'PORTG/BBQ', 'cuisine' => 'EUROPEAN', 'meta' => 'PORTUGUESE, BBQ'],
            ['s2' => 'PORTGS', 'cuisine' => 'EUROPEAN', 'meta' => 'PORTUGUESE'],
            ['s2' => 'PORTUEGE', 'cuisine' => 'EUROPEAN', 'meta' => 'PORTUGUESE'],
            ['s2' => 'PORTUGESE', 'cuisine' => 'EUROPEAN', 'meta' => 'PORTUGUESE'],
            ['s2' => 'PORTUGUESE', 'cuisine' => 'EUROPEAN', 'meta' => 'PORTUGUESE'],
            ['s2' => 'SWS', 'cuisine' => 'EUROPEAN', 'meta' => 'SWISS'],
            ['s2' => 'FILIP', 'cuisine' => 'FILIPINO', 'meta' => null ],
            ['s2' => 'FILIPINO', 'cuisine' => 'FILIPINO', 'meta' => null ],
            ['s2' => 'FRENCH', 'cuisine' => 'FRENCH', 'meta' => null ],
            ['s2' => 'FRH', 'cuisine' => 'FRENCH', 'meta' => null ],
            ['s2' => 'FRN/AM', 'cuisine' => 'FRENCH', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'As/Mex/Am', 'cuisine' => 'FUSION', 'meta' => 'ASIAN, AMERICAN, MEXICAN, , ASIAN, ORIENTAL'],
            ['s2' => 'ASN/FILP', 'cuisine' => 'FUSION', 'meta' => 'ASIAN, FILIPINO, ASIAN, ORIENTAL'],
            ['s2' => 'ASN/MEX', 'cuisine' => 'FUSION', 'meta' => 'ASIAN, MEXICAN, ASIAN, ORIENTAL'],
            ['s2' => 'Burm/Chn', 'cuisine' => 'FUSION', 'meta' => 'BURMESE, CHINESE, ASIAN, ORIENTAL'],
            ['s2' => 'CAT', 'cuisine' => 'FUSION', 'meta' => 'CATERING'],
            ['s2' => 'CHN/FILIP', 'cuisine' => 'FUSION', 'meta' => 'CHINESE, FILIPINO, ASIAN, ORIENTAL'],
            ['s2' => 'CHN/JPN', 'cuisine' => 'FUSION', 'meta' => 'CHINESE, JAPANESE, ASIAN, ORIENTAL'],
            ['s2' => 'CHN/KRN', 'cuisine' => 'FUSION', 'meta' => 'CHINESE, KOREAN, ASIAN, ORIENTAL'],
            ['s2' => 'CHN/MEX', 'cuisine' => 'FUSION', 'meta' => 'CHINESE, MEXICAN, ASIAN, ORIENTAL'],
            ['s2' => 'ECLECTI', 'cuisine' => 'FUSION', 'meta' => null ],
            ['s2' => 'ECLECTIC', 'cuisine' => 'FUSION', 'meta' => null ],
            ['s2' => 'FUSION', 'cuisine' => 'FUSION', 'meta' => null ],
            ['s2' => 'IND/ASN', 'cuisine' => 'FUSION', 'meta' => 'IDIAN, ASIAN'],
            ['s2' => 'JPN/CHN', 'cuisine' => 'FUSION', 'meta' => 'CHINESE, JAPANESE, ASIAN, ORIENTAL'],
            ['s2' => 'JPN/KRN', 'cuisine' => 'FUSION', 'meta' => 'JAPANESE, KOREAN, ASIAN, ORIENTAL'],
            ['s2' => 'KRN/JPN', 'cuisine' => 'FUSION', 'meta' => 'JAPANESE, KOREAN, ASIAN, ORIENTAL'],
            ['s2' => 'MEX/CUB', 'cuisine' => 'FUSION', 'meta' => 'MEIXCAN, CUBAN, CARRIBEAN'],
            ['s2' => 'MEX/HAW', 'cuisine' => 'FUSION', 'meta' => 'FUSION, MEXICAN, HAWAIIN'],
            ['s2' => 'MEX/ITL', 'cuisine' => 'FUSION', 'meta' => 'FUSION, MEXICAN, ITALIAN'],
            ['s2' => 'MIX', 'cuisine' => 'FUSION', 'meta' => null ],
            ['s2' => 'MULTIPLE', 'cuisine' => 'FUSION', 'meta' => null ],
            ['s2' => 'THAI/CHN', 'cuisine' => 'FUSION', 'meta' => 'THAI, CHINESE, ASIAN, ORIENTAL'],
            ['s2' => 'THAI/JPN', 'cuisine' => 'FUSION', 'meta' => 'THAI, JAPANESE, ASIAN, ORIENTAL'],
            ['s2' => 'VARIETY', 'cuisine' => 'FUSION', 'meta' => null ],
            ['s2' => 'BIEROCK', 'cuisine' => 'GERMAN', 'meta' => null ],
            ['s2' => 'GERMAN', 'cuisine' => 'GERMAN', 'meta' => null ],
            ['s2' => 'GRM/AM', 'cuisine' => 'GERMAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'GRM/AUS', 'cuisine' => 'GERMAN', 'meta' => null ],
            ['s2' => 'AM/GRK', 'cuisine' => 'GREEK', 'meta' => 'FUSION, AMERICAN, MEDITRN'],
            ['s2' => 'GREEK', 'cuisine' => 'GREEK', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'GRK', 'cuisine' => 'GREEK', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'GRK/AMER', 'cuisine' => 'GREEK', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'GRK/MED', 'cuisine' => 'GREEK', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'GRK/SEA', 'cuisine' => 'GREEK', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'GYRO', 'cuisine' => 'GREEK', 'meta' => 'MEDITERRANEAN, GYRO'],
            ['s2' => 'PITA', 'cuisine' => 'GREEK', 'meta' => 'MEDITERRANEAN, PITA'],
            ['s2' => 'PITAS', 'cuisine' => 'GREEK', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'GRILL', 'cuisine' => 'GRILL', 'meta' => null ],
            ['s2' => 'KABOB', 'cuisine' => 'GRILL', 'meta' => 'KABOB'],
            ['s2' => 'HAW/JPN', 'cuisine' => 'HAWAIIAN', 'meta' => 'FUSION, JAPANESE'],
            ['s2' => 'HAWAI', 'cuisine' => 'HAWAIIAN', 'meta' => null ],
            ['s2' => 'HAWAIIAN', 'cuisine' => 'HAWAIIAN', 'meta' => null ],
            ['s2' => 'HAWAIIN', 'cuisine' => 'HAWAIIAN', 'meta' => null ],
            ['s2' => 'HAWN', 'cuisine' => 'HAWAIIAN', 'meta' => null ],
            ['s2' => 'BURGER', 'cuisine' => 'HOTDOG/BURGER', 'meta' => 'HAMBURGER, BURGER, GRILL'],
            ['s2' => 'HBG', 'cuisine' => 'HOTDOG/BURGER', 'meta' => 'HAMBURGER, BURGER, GRILL'],
            ['s2' => 'HDS', 'cuisine' => 'HOTDOG/BURGER', 'meta' => 'HOTDOG, SAUSAGE, GRILL'],
            ['s2' => 'HOT DOG', 'cuisine' => 'HOTDOG/BURGER', 'meta' => 'HOTDOG, GRILL'],
            ['s2' => 'SRV', 'cuisine' => 'HOTDOG/BURGER', 'meta' => 'SPORT'],
            ['s2' => 'GELATO', 'cuisine' => 'ICE CREAM', 'meta' => 'GELATO'],
            ['s2' => 'ICE CREAM YOGURT', 'cuisine' => 'ICE CREAM', 'meta' => 'YOGURT'],
            ['s2' => 'ICE CREAM/YOGURT', 'cuisine' => 'ICE CREAM', 'meta' => 'YOGURT'],
            ['s2' => 'ICM', 'cuisine' => 'ICE CREAM', 'meta' => 'YOGURT'],
            ['s2' => 'RST DRIV IN DAIRY BR', 'cuisine' => 'ICE CREAM', 'meta' => null ],
            ['s2' => 'IND', 'cuisine' => 'INDIAN', 'meta' => null ],
            ['s2' => 'IND/PAK', 'cuisine' => 'INDIAN', 'meta' => 'PAKASTAN'],
            ['s2' => 'INDIAN', 'cuisine' => 'INDIAN', 'meta' => null ],
            ['s2' => 'NEPALI', 'cuisine' => 'INDIAN', 'meta' => 'NEPAL'],
            ['s2' => 'PAKISTAN', 'cuisine' => 'INDIAN', 'meta' => 'PAKASTAN'],
            ['s2' => 'PAKISTN', 'cuisine' => 'INDIAN', 'meta' => 'PAKASTAN'],
            ['s2' => 'S INDIAN', 'cuisine' => 'INDIAN', 'meta' => null ],
            ['s2' => 'W INDIAN', 'cuisine' => 'INDIAN', 'meta' => null ],
            ['s2' => 'INDO', 'cuisine' => 'INDONESIAN', 'meta' => null ],
            ['s2' => 'INDONESIA', 'cuisine' => 'INDONESIAN', 'meta' => null ],
            ['s2' => 'INDONESIAN', 'cuisine' => 'INDONESIAN', 'meta' => null ],
            ['s2' => 'MALAY', 'cuisine' => 'INDONESIAN', 'meta' => 'MALAYSIAN'],
            ['s2' => 'MALAYSIA', 'cuisine' => 'INDONESIAN', 'meta' => 'MALAYSIAN'],
            ['s2' => 'MALAYSIAN', 'cuisine' => 'INDONESIAN', 'meta' => 'MALAYSIAN'],
            ['s2' => 'AM/IRISH', 'cuisine' => 'IRISH', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'IRISH', 'cuisine' => 'IRISH', 'meta' => null ],
            ['s2' => 'IRISH/AM', 'cuisine' => 'IRISH', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'AM/ITL', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'CHK/ITL', 'cuisine' => 'ITALIAN', 'meta' => 'CHICKEN'],
            ['s2' => 'FRN/ITL', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, FRENCH'],
            ['s2' => 'ITALIAN', 'cuisine' => 'ITALIAN', 'meta' => null ],
            ['s2' => 'ITL', 'cuisine' => 'ITALIAN', 'meta' => 'ITALIAN'],
            ['s2' => 'ITL/AM', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'ITL/AMER', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'ITL/BRZ', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, BRAZILIAN'],
            ['s2' => 'ITL/CHK', 'cuisine' => 'ITALIAN', 'meta' => 'CHICKEN'],
            ['s2' => 'ITL/CHKN', 'cuisine' => 'ITALIAN', 'meta' => 'CHICKEN'],
            ['s2' => 'ITL/FRN', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, FRENCH'],
            ['s2' => 'ITL/JPN', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, JAPANESE'],
            ['s2' => 'ITL/MEX', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, MEXICAN'],
            ['s2' => 'ITL/PAST', 'cuisine' => 'ITALIAN', 'meta' => null ],
            ['s2' => 'ITL/SPN', 'cuisine' => 'ITALIAN', 'meta' => 'FUSION, SPANISH'],
            ['s2' => 'N ITALIAN', 'cuisine' => 'ITALIAN', 'meta' => null ],
            ['s2' => 'SEA/ITL', 'cuisine' => 'ITALIAN', 'meta' => 'SEAFOOD'],
            ['s2' => 'JAP', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAP/BBQ', 'cuisine' => 'JAPANESE', 'meta' => 'BBQ, ASIAN, ORIENTAL'],
            ['s2' => 'JAP/THAI', 'cuisine' => 'JAPANESE', 'meta' => 'FUSION, THAI, ASIAN, ORIENTAL'],
            ['s2' => 'JAPA', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAPAN', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAPANE', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAPANES', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAPANESE', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAPANS', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAPNESE', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JAPNSE', 'cuisine' => 'JAPANESE', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'JEW/JPN', 'cuisine' => 'JAPANESE', 'meta' => 'FUSION, JEWISH'],
            ['s2' => 'JPN/AM', 'cuisine' => 'JAPANESE', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'JUICE', 'cuisine' => 'JUICE BAR', 'meta' => 'HEALTH'],
            ['s2' => 'JUICE BAR', 'cuisine' => 'JUICE BAR', 'meta' => 'HEALTH'],
            ['s2' => 'JUICE SMOOTHIE', 'cuisine' => 'JUICE BAR', 'meta' => 'SMOOTHIE, HEALTH'],
            ['s2' => 'Smooth/Juice', 'cuisine' => 'JUICE BAR', 'meta' => 'SMOOTHIE, HEALTH'],
            ['s2' => 'SMOOTHIES', 'cuisine' => 'JUICE BAR', 'meta' => 'SMOOTHIE, HEALTH'],
            ['s2' => 'SMOOTIE', 'cuisine' => 'JUICE BAR', 'meta' => 'SMOOTHIE, HEALTH'],
            ['s2' => 'Chick/Krn', 'cuisine' => 'KOREAN', 'meta' => 'CHICKEN'],
            ['s2' => 'KOR', 'cuisine' => 'KOREAN', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'KOR/LAT', 'cuisine' => 'KOREAN', 'meta' => 'FUSION, LATIN, ASIAN, ORIENTAL'],
            ['s2' => 'KOREAN', 'cuisine' => 'KOREAN', 'meta' => 'ASIAN, ORIENTAL'],
            ['s2' => 'KRN/SEA', 'cuisine' => 'KOREAN', 'meta' => 'SEAFOOD, ASIAN, ORIENTAL'],
            ['s2' => 'Am/Kosher', 'cuisine' => 'KOSHER', 'meta' => 'AMERICAN, JEW'],
            ['s2' => 'Glat Kosher', 'cuisine' => 'KOSHER', 'meta' => 'JEW'],
            ['s2' => 'KOS', 'cuisine' => 'KOSHER', 'meta' => 'JEWISH'],
            ['s2' => 'Kosh/Stk', 'cuisine' => 'KOSHER', 'meta' => 'STEAKHOUSE, , JEW'],
            ['s2' => 'KOSHER', 'cuisine' => 'KOSHER', 'meta' => 'JEW'],
            ['s2' => 'AM/MED', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'FUSION, MEDITERRANEAN, AMERICAN'],
            ['s2' => 'CA/MED', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'FUSION, MEDITERRANEAN, CALIFORNIAN'],
            ['s2' => 'MED/AM', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'FUSION, MEDITERRANEAN, AMERICAN'],
            ['s2' => 'MED/AMER', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'FUSION, MEDITERRANEAN, AMERICAN'],
            ['s2' => 'MED/ITL', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN, ITALIAN'],
            ['s2' => 'Med/Romanian', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN, ROMANIAN'],
            ['s2' => 'MED/SEA', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN, SEAFOOD'],
            ['s2' => 'MEDIT', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'MEDITERR', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'MEDITERR/AMER', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN, FUSION, AMERICAN'],
            ['s2' => 'MEDITERRANEAN', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'MEDITR', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'MEDITRN', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'MEITERR', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN'],
            ['s2' => 'MOROC', 'cuisine' => 'MEDITERRANEAN', 'meta' => 'MEDITERRANEAN, MOROCCAN'],
            ['s2' => 'AM/MEX', 'cuisine' => 'MEXICAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'AMER/MEX', 'cuisine' => 'MEXICAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'AMR/MEX', 'cuisine' => 'MEXICAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'MEX', 'cuisine' => 'MEXICAN', 'meta' => null ],
            ['s2' => 'MEX/AM', 'cuisine' => 'MEXICAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'MEX/AMER', 'cuisine' => 'MEXICAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'MEX/AMR', 'cuisine' => 'MEXICAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'MEX/BBQ', 'cuisine' => 'MEXICAN', 'meta' => 'BBQ'],
            ['s2' => 'MEX/SAL', 'cuisine' => 'MEXICAN', 'meta' => 'SALVADOR, FUSION'],
            ['s2' => 'MEX/SEA', 'cuisine' => 'MEXICAN', 'meta' => 'SEAFOOD'],
            ['s2' => 'MEX/SLV', 'cuisine' => 'MEXICAN', 'meta' => 'SALVADOR, FUSION'],
            ['s2' => 'MEXAMR', 'cuisine' => 'MEXICAN', 'meta' => 'FUSION, AMERICAN'],
            ['s2' => 'MEXICAN', 'cuisine' => 'MEXICAN', 'meta' => null ],
            ['s2' => 'MEXICAN/LATIN', 'cuisine' => 'MEXICAN', 'meta' => 'LATIN AMERICAN'],
            ['s2' => 'S MEXICN', 'cuisine' => 'MEXICAN', 'meta' => null ],
            ['s2' => 'SEA/MEX', 'cuisine' => 'MEXICAN', 'meta' => 'SEAFOOD'],
            ['s2' => 'AFGHAN', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, AFGHAN'],
            ['s2' => 'AM/ MID E', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, AMERICAN, FUSION'],
            ['s2' => 'AM/TRK', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, FUSION, AMERICAN, TURKEY, TURKISH, GRILL'],
            ['s2' => 'EAS', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN'],
            ['s2' => 'LEB', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, LEBANESE, MEDITERRANEAN'],
            ['s2' => 'LEBANE', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, LEBANESE'],
            ['s2' => 'LEBANESE', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, LEBANESE'],
            ['s2' => 'LEBANSE', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, LEBANESE'],
            ['s2' => 'LEBNSE', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, LEBANESE'],
            ['s2' => 'MID E/ITL', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, ITALIAN, FUSION'],
            ['s2' => 'MID EASGT', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN'],
            ['s2' => 'MID EAST', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN'],
            ['s2' => 'MID EASTERN', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN'],
            ['s2' => 'MIDDLE EAST', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN'],
            ['s2' => 'MIDDLE EASTERN', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN'],
            ['s2' => 'MIDEAST', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN'],
            ['s2' => 'MOR', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MOROCCAN'],
            ['s2' => 'TURKISH', 'cuisine' => 'MIDDLE EAST', 'meta' => 'MIDDLE EASTERN, TURKISH, TURKEY'],
            ['s2' => 'Albn/Itl', 'cuisine' => 'OTHER', 'meta' => 'ITALIAN'],
            ['s2' => 'BICOASTAL', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'Bosn/Am', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'CHF', 'cuisine' => 'OTHER', 'meta' => 'CAFETERIA, SCHOOL, UNIVERSITY, COLLEGE'],
            ['s2' => 'ETHNIC', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'FFY', 'cuisine' => 'OTHER', 'meta' => 'RELIGION, CHURCH'],
            ['s2' => 'FINE DINING', 'cuisine' => 'OTHER', 'meta' => 'FINE DINING'],
            ['s2' => 'FONDUE', 'cuisine' => 'OTHER', 'meta' => 'FONDUE'],
            ['s2' => 'GLOBAL', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'GOURM', 'cuisine' => 'OTHER', 'meta' => 'GOURMET'],
            ['s2' => 'GOURMET', 'cuisine' => 'OTHER', 'meta' => 'GOURMET'],
            ['s2' => 'GOURMT', 'cuisine' => 'OTHER', 'meta' => 'GOURMET'],
            ['s2' => 'HEALTH', 'cuisine' => 'OTHER', 'meta' => 'HEALTHFOOD, HEALTHY'],
            ['s2' => 'HEALTHY', 'cuisine' => 'OTHER', 'meta' => 'HEALTHFOOD, HEALTHY'],
            ['s2' => 'HIMALYN', 'cuisine' => 'OTHER', 'meta' => 'HIMALAYAN, INDIAN'],
            ['s2' => 'INTERNL', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'INTL', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'INV', 'cuisine' => 'OTHER', 'meta' => 'INVALID'],
            ['s2' => 'LGU', 'cuisine' => 'OTHER', 'meta' => 'LODGING, UPSCALE'],
            ['s2' => 'LIMITED', 'cuisine' => 'OTHER', 'meta' => 'LIMITED SERVICE'],
            ['s2' => 'LIMITED MENU', 'cuisine' => 'OTHER', 'meta' => 'LIMITED SERVICE'],
            ['s2' => 'N/A', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'ORGANIC', 'cuisine' => 'OTHER', 'meta' => 'ORGANIC, HEALTH'],
            ['s2' => 'OTH', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'OTHER', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'POTATO', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'RGNLAM', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'SCH', 'cuisine' => 'OTHER', 'meta' => 'SCHOOL, CAFETERIA, UNIVERSITY, COLLEGE'],
            ['s2' => 'SEASON', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'SEASONL', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'SPECIAL', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'SPECIALTY', 'cuisine' => 'OTHER', 'meta' => null ],
            ['s2' => 'PER', 'cuisine' => 'PERSIAN', 'meta' => 'MIDDLE EASTERN, IRANIAN'],
            ['s2' => 'PER/SPN', 'cuisine' => 'PERSIAN', 'meta' => 'MIDDLE EASTERN, IRANIAN'],
            ['s2' => 'PERS/IND', 'cuisine' => 'PERSIAN', 'meta' => 'MIDDLE EASTERN, FUSION, INDIAN, IRANIAN'],
            ['s2' => 'PERSHIAN', 'cuisine' => 'PERSIAN', 'meta' => 'MIDDLE EASTERN, IRANIAN'],
            ['s2' => 'PERSIAN', 'cuisine' => 'PERSIAN', 'meta' => 'MIDDLE EASTERN, IRANIAN'],
            ['s2' => 'ITALIAN & PIZZA', 'cuisine' => 'PIZZA', 'meta' => 'ITALIAN'],
            ['s2' => 'PIZZA', 'cuisine' => 'PIZZA', 'meta' => 'ITALIAN'],
            ['s2' => 'PZZ', 'cuisine' => 'PIZZA', 'meta' => 'ITALIAN'],
            ['s2' => 'RUS', 'cuisine' => 'RUSSIAN', 'meta' => 'ASIAN, EUROP'],
            ['s2' => 'RUSSIAN', 'cuisine' => 'RUSSIAN', 'meta' => 'ASIAN, EUROP'],
            ['s2' => 'RUSSN', 'cuisine' => 'RUSSIAN', 'meta' => 'ASIAN, EUROP'],
            ['s2' => 'SALAD', 'cuisine' => 'SALAD BAR', 'meta' => 'SOUP'],
            ['s2' => 'SALAD/SOUP', 'cuisine' => 'SALAD BAR', 'meta' => 'SOUP'],
            ['s2' => 'CATERER DELI', 'cuisine' => 'SANDWICH', 'meta' => 'DELI, SUB'],
            ['s2' => 'DEL', 'cuisine' => 'SANDWICH', 'meta' => 'DELI, SUB'],
            ['s2' => 'SANDWC', 'cuisine' => 'SANDWICH', 'meta' => 'DELI, SUB'],
            ['s2' => 'SANDWICH', 'cuisine' => 'SANDWICH', 'meta' => 'DELI, SUB'],
            ['s2' => 'SDW', 'cuisine' => 'SANDWICH', 'meta' => 'DELI, SUB'],
            ['s2' => 'AM/SEA', 'cuisine' => 'SEAFOOD', 'meta' => 'FISH'],
            ['s2' => 'CHK/SEA', 'cuisine' => 'SEAFOOD', 'meta' => 'CHICKEN, FISH'],
            ['s2' => 'SEA/AM', 'cuisine' => 'SEAFOOD', 'meta' => 'FISH'],
            ['s2' => 'SEA/CHK', 'cuisine' => 'SEAFOOD', 'meta' => 'CHICKEN, FISH'],
            ['s2' => 'SEAFOOD', 'cuisine' => 'SEAFOOD', 'meta' => 'FISH'],
            ['s2' => 'SFD', 'cuisine' => 'SEAFOOD', 'meta' => 'FISH'],
            ['s2' => 'SOUL', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'SOUL F', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'SOUL FO', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'SOUL FOO', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'SOUL FOOD', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'SOULFOOD', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'SOUTHERN', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'SOUTHRN', 'cuisine' => 'SOUL FOOD', 'meta' => 'SOUTHERN'],
            ['s2' => 'AGENTIAN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'ARGENTINIAN, GRILL'],
            ['s2' => 'AM/ S AM', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'AMERICAN'],
            ['s2' => 'ARGENT', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'ARGENTINIAN, GRILL'],
            ['s2' => 'ARGENTI', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'ARGENTINIAN, GRILL'],
            ['s2' => 'BRAZIL', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'BRAZILIAN'],
            ['s2' => 'BRAZILIAN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'BRAZILIAN'],
            ['s2' => 'BRAZLN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'BRAZILIAN'],
            ['s2' => 'COLOM', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'COLUMBIAN'],
            ['s2' => 'COLOMB', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'COLUMBIAN'],
            ['s2' => 'COLUM', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'COLUMBIAN'],
            ['s2' => 'COLUMBIA', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'COLUMBIAN'],
            ['s2' => 'ECUADO', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'ECUADORIAN'],
            ['s2' => 'ECUADR', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'ECUADORIAN'],
            ['s2' => 'ECUADRN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'ECUADORIAN'],
            ['s2' => 'EL SALV', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'SALVADORAN, EL SALVADORIAN'],
            ['s2' => 'GUATAM', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'SALVADORAN, EL SALVADORIAN'],
            ['s2' => 'HONDRN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'HONDURAN'],
            ['s2' => 'LAT AM', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'LATIN AMERICAN'],
            ['s2' => 'LATIN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'LATIN AMERICAN'],
            ['s2' => 'LATIN AM', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'LATIN AMERICAN'],
            ['s2' => 'Latin/Sea', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'LATIN AMERICAN, SEAFOOD'],
            ['s2' => 'LATINO', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'LATIN AMERICAN'],
            ['s2' => 'NICAR', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'NICARAGUA'],
            ['s2' => 'PERUVI', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'PERUVIAN'],
            ['s2' => 'PERUVIA', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'PERUVIAN'],
            ['s2' => 'PERUVIAN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'PERUVIAN'],
            ['s2' => 'PERUVN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'PERUVIAN'],
            ['s2' => 'PERV/CRB', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'PERUVIAN, CARRIBEAN, FUSION'],
            ['s2' => 'S AMERICAN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'GRILL'],
            ['s2' => 'S. AMER', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'GRILL'],
            ['s2' => 'SALVADORAN', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'SALVADORAN, EL SALVADORIAN'],
            ['s2' => 'SALVD', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'SALVADORAN, EL SALVADORIAN'],
            ['s2' => 'SALVDR', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'SALVADORAN, EL SALVADORIAN'],
            ['s2' => 'SMX', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'MEXICAN'],
            ['s2' => 'STA', 'cuisine' => 'SOUTH AMERICAN', 'meta' => 'LATIN'],
            ['s2' => 'S.WEST', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'S.WESTERN', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'SOTHWEST', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'SOTHWESTERN', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'SOUTH AMERICAN', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'SOUTHWEST', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'SOUTHWESTERN', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'SWEST', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'SWN', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'CHILI, GRILL'],
            ['s2' => 'TEX MEX', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'FUSION, MEXICAN, AMERICAN, TEX-MEX, CHILI, GRILL'],
            ['s2' => 'TEX-MEX', 'cuisine' => 'SOUTHWESTERN', 'meta' => 'FUSION, MEXICAN, AMERICAN, TEX-MEX, CHILI, GRILL'],
            ['s2' => 'AM/SPN', 'cuisine' => 'SPANISH', 'meta' => 'AMERICAN, FUSION, TAPAS'],
            ['s2' => 'SPANISH', 'cuisine' => 'SPANISH', 'meta' => 'TAPAS'],
            ['s2' => 'SPN', 'cuisine' => 'SPANISH', 'meta' => 'TAPAS'],
            ['s2' => 'TAPAS', 'cuisine' => 'SPANISH', 'meta' => 'TAPAS'],
            ['s2' => 'SEA/STK', 'cuisine' => 'STEAK/SEAFOOD', 'meta' => 'GRILL, FISH, MEAT'],
            ['s2' => 'SEAFOOD & STEAK', 'cuisine' => 'STEAK/SEAFOOD', 'meta' => 'GRILL, FISH, MEAT'],
            ['s2' => 'SEAFOOD/STEAK', 'cuisine' => 'STEAK/SEAFOOD', 'meta' => 'GRILL, FISH, MEAT'],
            ['s2' => 'STEAK & SEAFOOD', 'cuisine' => 'STEAK/SEAFOOD', 'meta' => 'GRILL, FISH, MEAT'],
            ['s2' => 'STEAK/SEAFOOD', 'cuisine' => 'STEAK/SEAFOOD', 'meta' => 'GRILL, FISH, MEAT'],
            ['s2' => 'STK', 'cuisine' => 'STEAK/SEAFOOD', 'meta' => 'GRILL'],
            ['s2' => 'STK/SEA', 'cuisine' => 'STEAK/SEAFOOD', 'meta' => 'GRILL, FISH, MEAT'],
            ['s2' => 'STEAK', 'cuisine' => 'STEAKHOUSE', 'meta' => 'GRILL'],
            ['s2' => 'STEAKHOUSE', 'cuisine' => 'STEAKHOUSE', 'meta' => 'GRILL'],
            ['s2' => 'SUSHI', 'cuisine' => 'SUSHI', 'meta' => 'JAPANESE, ASIAN, ORIENTAL'],
            ['s2' => 'THAI', 'cuisine' => 'THAI', 'meta' => null ],
            ['s2' => 'THAI/LAO', 'cuisine' => 'THAI', 'meta' => null ],
            ['s2' => 'THI', 'cuisine' => 'THAI', 'meta' => null ],
            ['s2' => 'TIBETN', 'cuisine' => 'THAI', 'meta' => 'TIBETAN'],
            ['s2' => 'HLF', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'RAW/VEG', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'TOFU', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEG', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEG/AM', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEGAN', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEGET', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEGETARIAN', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEGETARIN', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEGETR', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'VEGITARIAN', 'cuisine' => 'VEGETARIAN', 'meta' => 'TOFU, HEALTH, VEGAN'],
            ['s2' => 'CAMBOD', 'cuisine' => 'VIETNAMESE', 'meta' => 'CAMBODIAN'],
            ['s2' => 'FRN/VTN', 'cuisine' => 'VIETNAMESE', 'meta' => 'FUSION, FRENCH'],
            ['s2' => 'VIE', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIENTMS', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIET', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIET/CHN', 'cuisine' => 'VIETNAMESE', 'meta' => 'FUSION, CHINESE'],
            ['s2' => 'VIETMSE', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIETN', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIETNA', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIETNAM', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIETNAME', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIETNAMESE', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIETNM', 'cuisine' => 'VIETNAMESE', 'meta' => null ],
            ['s2' => 'VIETNMS', 'cuisine' => 'VIETNAMESE', 'meta' => null ]

        ];

        DB::table('cuisines')
          ->insert($cuisines);
    }
}
